spring:
    application:
        name: rabbitmqapplication
    rabbitmq:
        queue-name: notification.email.queue
        exchange-name: app.exchange
        routing-key: notification.email.routingkey
        

rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest